name: Flutter CI

on: [push, pull_request]
  # push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

# permissions:
#   contents: read

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    # timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.8'
          channel: 'stable'
      - name: Install Flutter Packages
        run: |
          flutter pub get
          flutter pub run build_runner build
      - name: Test
        run: flutter test --coverage
      - name: Show Coverage Report
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 0
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./